name: Update project documentation

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request: # For testing purposes only, delete before pushing to main
    branches: [ "main" ]

jobs:
  upload-documentation:
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: '.draka-o-hajs/Docs'
          doxyfile-path: '.draka-o-hajs/Docs/Doxyfile'

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs/html